### ISSUE TITLE
Team convention

### ISSUE THREAD

**Issue by jabichris** [sz16900/heat_map_smashing_mag#3]
It is better to have team conventions and rules for clear code. for example, someone is using  `px` and another one is using `em`, `rem`. It's better to keep one measurement and keep it everywhere in the codebase?

**Comment by Flakster** [comment]
To improve your code consistency remember to decide what color notation are you going to use through your whole style files: color code, hex values, rgb, etc.

**Comment by sz16900** [comment]
Thanks guys. All of these issues have been solved.
